[package]
name = "kime-train"
description = "Training, distillation and calibration fitting for kime models."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
kime-core.workspace = true
kime-model.workspace = true

[lints]
workspace = true
