[package]
name = "kime-cpu"
description = "The CPU backend for kime: x86 and ARM kernels, FP32 and INT8."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
kime-tensor.workspace = true

[lints]
workspace = true
